### ISSUE TITLE
Code I had for totals of strata isn't working

### ISSUE THREAD

**Issue by dlaurison** [corybrunson/ggalluvial#113] opened 2023-03-25 19:14 UTC
### Description of the issue

I have a diagram where I want both the totals for each flow marked in near the flows - and I've got that working - and the total for each stratum near the strata/lode. I had it working but it's stopped.  (last definitely worked in July 2022.) 

Here is the code I'm using (it may be hacky, R is not my native stats language) 
The line that makes the totals show up, and that has stopped working, is     geom_text(aes(label=round(Freq, digits = 2)), stat = "stratum", nudge_x = -.2) +

Fig1<-ggplot(od44, aes(y=Freq, axis1=origin, axis2=dclass4)) +
  geom_alluvium(aes(fill=origin), width=1/4, reverse=TRUE) +
geom_stratum(width=1/4, alpha=0, reverse=TRUE, color="black") +
    scale_x_discrete(limits= c("Origin","Destination"), expand=c(.2, .2))  +
    geom_text(stat = "stratum", infer.label = TRUE, reverse = TRUE) +
    geom_text(aes(label=sprintf("%0.2f", round(Freq, digits = 2))), stat = "flow", nudge_x = .2) +
 geom_text(stat = "stratum", aes(label = paste(after_stat(stratum)))) +
  scale_fill_manual(values = c("darkcyan", "deepskyblue", "darkgoldenrod2", "darkmagenta"))+
  theme_minimal() +
theme(axis.title.y = element_blank(), axis.text.y= element_blank(), legend.position = "none" , plot.title=element_text(hjust=0.5), axis.text.x =element_blank()) +
  ggtitle("Class Origin and Destination")

1st image is what I'm currently seeing; 2nd image is what I want to see/used to get. (the underlying data are slightly different now, so numbers are different, but that's not the issue).

![image](https://user-images.githubusercontent.com/128930375/227737006-8b7aeff0-733e-4b64-a32c-2c47b8fdb581.png)

![Figure 1](https://user-images.githubusercontent.com/128930375/227737048-ceff0918-29f0-4671-9b94-07ada61f6a19.png)

**Comment by corybrunson** [comment] 2023-03-25 22:47
Hi @dlaurison and thanks for raising the issue. I'm not completely sure about the reason for the difference, since i don't have a toy sample of data to work with. (If you could provide a small data set that mimics the structure and reproduces the problem, that would be extremely helpful, if this comment doesn't help.)

Am i right that there's a mismatch between your description of the problem, which uses `stat = "stratum"`, and the code in your snippet, which uses `stat = "flow"` for the rounded `Freq` values (line 6)? I adapted a toy example from one of the vignettes to try what happens under different ways of incorporating a numerical column for labeling purposes. The code below uses `stat = "flow"`, but you can try executing it with `stat = "stratum"` instead (as indicated by comments).

The labels appear for all geometric objects in the second plot, because the numerical values have been added and these sums are being used as labels (`after_stat(count)`; see the discussion of computed variables in the documentation). But they are missing in the first plot, when plotting strata, since the raw `val` values are being used as labels, and these values aren't defined for strata that include more than one lode (hence more than one value of `val`). So the problem may be resolved by replacing `round(Freq, digits = 2)` with `round(after_stat(count), digits = 2)` in your code. Note that this would work only because `Freq` is passed to the `y` aesthetic, hence `count` is computed automatically from it.

Please let me know if that works! If not, we can try something else.

``` r
library(ggalluvial)
#> Loading required package: ggplot2

# toy data set
set.seed(0)
toy <- data.frame(
  subject = rep(LETTERS[1:5], times = 4),
  collection = rep(1:4, each  = 5),
  category = rep(
    sample(c("X", "Y"), 16, replace = TRUE),
    rep(c(1, 2, 1, 1), times = 4)
  ),
  class = c("one", "one", "one", "two", "two"),
  val = runif(n = 20)
)
print(toy)
#>    subject collection category class        val
#> 1        A          1        Y   one 0.49769924
#> 2        B          1        X   one 0.71761851
#> 3        C          1        X   one 0.99190609
#> 4        D          1        Y   two 0.38003518
#> 5        E          1        X   two 0.77744522
#> 6        A          2        X   one 0.93470523
#> 7        B          2        Y   one 0.21214252
#> 8        C          2        Y   one 0.65167377
#> 9        D          2        X   two 0.12555510
#> 10       E          2        X   two 0.26722067
#> 11       A          3        X   one 0.38611409
#> 12       B          3        Y   one 0.01339033
#> 13       C          3        Y   one 0.38238796
#> 14       D          3        Y   two 0.86969085
#> 15       E          3        X   two 0.34034900
#> 16       A          4        X   one 0.48208012
#> 17       B          4        X   one 0.59956583
#> 18       C          4        X   one 0.49354131
#> 19       D          4        X   two 0.18621760
#> 20       E          4        X   two 0.82737332

ggplot(toy, aes(x = collection, stratum = category, alluvium = subject,
                y = val)) +
  stat_stratum() +
  stat_flow(aes(fill = class)) +
  stat_flow(geom = "text",
            aes(label = subject, hjust = after_stat(flow) == "to")) +
  # try toggling between `"flow"` and `"stratum"` here
  geom_text(stat = "stratum", nudge_x = .3,
            aes(label = round(val, digits = 2)))
#> Warning: Removed 7 rows containing missing values (`geom_text()`).
```

![](https://i.imgur.com/O6RrND6.png)

``` r

ggplot(toy, aes(x = collection, stratum = category, alluvium = subject,
                y = val)) +
  stat_stratum() +
  stat_flow(aes(fill = class)) +
  stat_flow(geom = "text",
            aes(label = subject, hjust = after_stat(flow) == "to")) +
  # try toggling between `"flow"` and `"stratum"` here
  geom_text(stat = "stratum", nudge_x = .3,
            aes(label = round(after_stat(count), digits = 2)))
```

![](https://i.imgur.com/18CRBTx.png)

<sup>Created on 2023-03-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dlaurison** [comment] 2023-03-26 20:09
that worked, despite my incomplete description of the problem & lack of a toy dataset. Thank you!

**Comment by corybrunson** [comment] 2023-03-26 20:24
Excellent! Thank you for confirming.

**Closed by corybrunson** 2023-03-26 20:24 UTC
