### ISSUE TITLE
White lines within flow between axes

### ISSUE THREAD

**Issue by marijn1990** [corybrunson/ggalluvial#23] opened 2018-10-04 14:45 UTC
Hi Cory (and others), as discussed on Twitter: I am making alluvial diagrams using _ggalluvial_ but have encountered a problem. Briefly, I am comparing microbiome membership categories per participant between two visits (visit1, visit2). The flows between the two axis, however, show white lines between the different participants which probably bothers me more than it should ^^. When using ```tiff``` at a high resolution (e..g. res=900) this improves a bit, but it is still visible on an A4-sized print.

I have added an example data .txt file for illustration:
[example_dataset.txt](https://github.com/corybrunson/ggalluvial/files/2446723/example_dataset.txt)
I used the following code in R:

```
example_dataset <- read.delim("example_dataset.txt",row.names=1,check.names=FALSE,sep=",")
example_dataset <- as.data.frame(example_dataset)
value <- c("#000000", "#DC0000", "#FF9600", "#329600", "#000000", "#DC0000", "#FF9600", "#329600")
N <- ggplot(data = example_dataset, aes(axis1 = visit1, axis2 = visit2)) +
     scale_x_discrete(limits=c("visit 1", "visit 2")) +
	 geom_alluvium(fill = "darkgrey", na.rm = TRUE) +
	 geom_stratum(width = 1/3, fill = value) + 
	 labs(y="", x="Event") + 
     theme_light() + theme(panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(), panel.grid.minor.y =  element_blank())

tiff(filename="example.jpg", width=10, height=8, units="in", res=50)
N
dev.off()
```

I get this image:
![image](https://user-images.githubusercontent.com/36040340/46481989-7ee5d180-c7ec-11e8-81df-0dfcd613ec17.png)

Any idea how to improve this image? As said, increasing the resolution did not improve much. Thank you for your help!

**Comment by mbojan** [comment] 2018-10-04 15:05
My intuition is that you have multiple rows such as, say, `visit1=orange` and `visit2=green` so that multiple alluvia are drawn.

**Comment by corybrunson** [comment] 2018-10-04 16:37
@marijn1990 i've reproduced the behavior, thanks! I don't think the issue is that alluvia are _overlapping_, which is what i read @mbojan to be suggesting (is that right?). Rather, _separate_ alluvia are being drawn for each row of data, and since they're drawn adjacent to each other a slight gap remains between them.

Using your code, i've found two ways to prevent this. One is to use the `aggregate.y` parameter in the alluvium layer, i.e. instead of
```r
geom_alluvium(fill = "darkgrey", na.rm = TRUE)
```
write
```r
geom_alluvium(fill = "darkgrey", na.rm = TRUE, aggregate.y = TRUE)
```
. The other is to make a flow layer instead of an alluvium layer, i.e.
```r
geom_flow(fill = "darkgrey", na.rm = TRUE)
```
. Please give those two changes a try! They have slightly different behavior, but in both cases (for me) the thin white lines go away.

**Comment by mbojan** [comment] 2018-10-04 18:29
Yep, I meant distinct "parallel" alluvia for separate rows linking the same categories (color rectangles).

**Comment by marijn1990** [comment] 2018-10-05 08:01
That works very well! The only issue that still remains that one line persists at the level between ```visit2=orange``` and ```visit2=red```, as these are still considered two different alluvia after aggregation, but that can be solved by hand. Thank you very much for your help!

**Comment by corybrunson** [comment] 2018-10-05 12:15
@marijn1990 you're right—those are still separate flows, in my implementation. Sorry! I don't have plans to change this, since i personally prefer it, but i'll leave this issue open for now, in case others would support making an option available to change it. (I'd also welcome a pull request.)

**Comment by marijn1990** [comment] 2018-10-05 12:46
@corybrunson I agree, I think there are many cases in which a separation between alluvia is preferable. Thanks again!

**Comment by modche** [comment] 2022-07-25 21:09
> @marijn1990 i've reproduced the behavior, thanks! I don't think the issue is that alluvia are _overlapping_, which is what i read @mbojan to be suggesting (is that right?). Rather, _separate_ alluvia are being drawn for each row of data, and since they're drawn adjacent to each other a slight gap remains between them.
> 
> Using your code, i've found two ways to prevent this. One is to use the `aggregate.y` parameter in the alluvium layer, i.e. instead of
> 
> ```r
> geom_alluvium(fill = "darkgrey", na.rm = TRUE)
> ```
> 
> write
> 
> ```r
> geom_alluvium(fill = "darkgrey", na.rm = TRUE, aggregate.y = TRUE)
> ```
> 
> . The other is to make a flow layer instead of an alluvium layer, i.e.
> 
> ```r
> geom_flow(fill = "darkgrey", na.rm = TRUE)
> ```
> 
> . Please give those two changes a try! They have slightly different behavior, but in both cases (for me) the thin white lines go away.

This helps a lot! Should be in the examples!

**Comment by corybrunson** [comment] 2023-01-08 13:54
I lost track of this! Reopening to remind myself to consider a new example.

**Comment by corybrunson** [comment] 2023-07-09 19:14
I believe this has been addressed in [some `stat_alluvium()` examples](http://corybrunson.github.io/ggalluvial/reference/stat_alluvium.html), using the renamed parameter `cement.alluvia`. Please feel free to reopen this issue if these examples miss something crucial that was resolved here.

**Closed by corybrunson** 2023-07-09 19:14 UTC
